name: ecommerce_analytics
version: "1.0.0"
config-version: 2

profile: ecommerce_analytics

model-paths: [models]
test-paths: [tests]

models:
  ecommerce_analytics:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table
